# Generated by Yosys 0.8+17 (git sha1 11c8a9eb, gcc 7.3.0-27ubuntu1~18.04 -fPIC -Os)
autoidx 121
attribute \cells_not_processed 1
attribute \src "device.v:1"
module \Controller
  attribute \src "device.v:3"
  wire width 32 inout 7 \AD
  attribute \src "device.v:2"
  wire width 4 input 2 \BE
  attribute \src "device.v:3"
  wire width 4 inout 8 \C_BE
  attribute \src "device.v:3"
  wire input 6 \clk
  attribute \src "device.v:2"
  wire width 2 input 1 \devaddress
  attribute \src "device.v:3"
  wire inout 9 \devsel
  attribute \src "device.v:10"
  wire \fcount
  attribute \src "device.v:10"
  wire \fend_count
  attribute \src "device.v:10"
  wire \ffinished
  attribute \src "device.v:2"
  wire input 3 \force_req
  attribute \src "device.v:3"
  wire inout 10 \frame
  attribute \src "device.v:10"
  wire \freq_pending
  attribute \src "device.v:11"
  wire \fvalid
  attribute \src "device.v:4"
  wire input 13 \gnt
  attribute \src "device.v:3"
  wire inout 11 \irdy
  attribute \src "device.v:2"
  wire input 4 \rd_wr
  attribute \src "device.v:4"
  wire output 14 \req
  attribute \src "device.v:7"
  wire width 3 \state
  attribute \src "device.v:3"
  wire inout 12 \trdy
  attribute \src "device.v:2"
  wire width 32 input 5 \write_data
  attribute \module_not_derived 1
  attribute \src "device.v:13"
  cell \Initiator_Controller \ic
    connect $1 \devaddress
    connect $10 \irdy
    connect $11 \req
    connect $12 \state
    connect $13 \fcount
    connect $14 \fend_count
    connect $15 \freq_pending
    connect $16 \ffinished
    connect $17 \fvalid
    connect $2 \BE
    connect $3 \force_req
    connect $4 \rd_wr
    connect $5 \write_data
    connect $6 \clk
    connect $7 \AD
    connect $8 \C_BE
    connect $9 \frame
  end
  attribute \module_not_derived 1
  attribute \src "device.v:9"
  cell \State_Machine \sm
    connect $1 \frame
    connect $10 \rd_wr
    connect $11 \fcount
    connect $12 \fend_count
    connect $13 \freq_pending
    connect $14 \ffinished
    connect $15 \fvalid
    connect $2 \irdy
    connect $3 \trdy
    connect $4 \devsel
    connect $5 \state
    connect $6 \clk
    connect $7 \force_req
    connect $8 \req
    connect $9 \gnt
  end
  attribute \module_not_derived 1
  attribute \src "device.v:18"
  cell \Target_Controller \tc
    connect $1 \clk
    connect $2 \AD
    connect $3 \C_BE
    connect $4 \devsel
    connect $5 \trdy
    connect $6 \state
    connect $7 \fvalid
  end
end
attribute \cells_not_processed 1
attribute \src "initiator.v:1"
module \Initiator_Controller
  parameter \address
  parameter \data
  parameter \finish
  parameter \idle
  parameter \turnaround
  attribute \src "initiator.v:10"
  wire width 32 $0$memwr$\memory$initiator.v:12$1_ADDR[31:0]$5
  attribute \src "initiator.v:10"
  wire width 32 $0$memwr$\memory$initiator.v:12$1_DATA[31:0]$6
  attribute \src "initiator.v:10"
  wire width 32 $0$memwr$\memory$initiator.v:12$1_EN[31:0]$7
  attribute \src "initiator.v:10"
  wire width 3 $0$memwr$\memory$initiator.v:14$2_ADDR[2:0]$8
  attribute \src "initiator.v:10"
  wire width 32 $0$memwr$\memory$initiator.v:14$2_DATA[31:0]$9
  attribute \src "initiator.v:10"
  wire width 32 $0$memwr$\memory$initiator.v:14$2_EN[31:0]$10
  attribute \src "initiator.v:71"
  wire width 3 $0$memwr$\memory$initiator.v:73$3_ADDR[2:0]$62
  attribute \src "initiator.v:71"
  wire width 32 $0$memwr$\memory$initiator.v:73$3_DATA[31:0]$63
  attribute \src "initiator.v:71"
  wire width 32 $0$memwr$\memory$initiator.v:73$3_EN[31:0]$64
  attribute \src "initiator.v:40"
  wire $0\bus_is_mine[0:0]
  attribute \src "initiator.v:10"
  wire width 4 $0\byte_enable[3:0]
  attribute \src "initiator.v:10"
  wire width 4 $0\command[3:0]
  attribute \src "initiator.v:25"
  wire width 2 $0\counter[1:0]
  attribute \src "initiator.v:71"
  wire width 3 $0\mp[2:0]
  attribute \src "initiator.v:40"
  wire $1\bus_is_mine[0:0]
  attribute \src "initiator.v:25"
  wire width 2 $1\counter[1:0]
  attribute \src "initiator.v:79"
  wire width 3 $1\mp[2:0]
  attribute \src "initiator.v:40"
  wire $2\bus_is_mine[0:0]
  attribute \src "initiator.v:25"
  wire width 2 $2\counter[1:0]
  attribute \src "initiator.v:40"
  wire $3\bus_is_mine[0:0]
  attribute \src "initiator.v:33"
  wire width 2 $3\counter[1:0]
  attribute \src "initiator.v:27"
  wire width 32 $add$initiator.v:27$12_Y
  attribute \src "initiator.v:81"
  wire width 32 $add$initiator.v:81$75_Y
  attribute \src "initiator.v:29"
  wire $eq$initiator.v:29$13_Y
  attribute \src "initiator.v:44"
  wire $eq$initiator.v:44$23_Y
  attribute \src "initiator.v:53"
  wire $eq$initiator.v:53$27_Y
  attribute \src "initiator.v:56"
  wire $eq$initiator.v:56$33_Y
  attribute \src "initiator.v:56"
  wire $eq$initiator.v:56$36_Y
  attribute \src "initiator.v:56"
  wire $eq$initiator.v:56$37_Y
  attribute \src "initiator.v:57"
  wire $eq$initiator.v:57$43_Y
  attribute \src "initiator.v:57"
  wire $eq$initiator.v:57$45_Y
  attribute \src "initiator.v:60"
  wire $eq$initiator.v:60$48_Y
  attribute \src "initiator.v:60"
  wire $eq$initiator.v:60$49_Y
  attribute \src "initiator.v:60"
  wire $eq$initiator.v:60$52_Y
  attribute \src "initiator.v:72"
  wire $eq$initiator.v:72$65_Y
  attribute \src "initiator.v:72"
  wire $eq$initiator.v:72$68_Y
  attribute \src "initiator.v:75"
  wire $eq$initiator.v:75$70_Y
  attribute \src "initiator.v:80"
  wire $eq$initiator.v:80$72_Y
  attribute \src "initiator.v:53"
  wire width 32 $extend$initiator.v:53$31_Y
  attribute \src "initiator.v:60"
  wire width 32 $extend$initiator.v:60$54_Y
  attribute \src "initiator.v:53"
  wire $gt$initiator.v:53$28_Y
  attribute \src "initiator.v:29"
  wire $logic_and$initiator.v:29$14_Y
  attribute \src "initiator.v:29"
  wire $logic_and$initiator.v:29$15_Y
  attribute \src "initiator.v:39"
  wire $logic_and$initiator.v:39$18_Y
  attribute \src "initiator.v:39"
  wire $logic_and$initiator.v:39$20_Y
  attribute \src "initiator.v:47"
  wire $logic_and$initiator.v:47$24_Y
  attribute \src "initiator.v:53"
  wire $logic_and$initiator.v:53$26_Y
  attribute \src "initiator.v:56"
  wire $logic_and$initiator.v:56$34_Y
  attribute \src "initiator.v:56"
  wire $logic_and$initiator.v:56$38_Y
  attribute \src "initiator.v:57"
  wire $logic_and$initiator.v:57$44_Y
  attribute \src "initiator.v:60"
  wire $logic_and$initiator.v:60$51_Y
  attribute \src "initiator.v:60"
  wire $logic_and$initiator.v:60$53_Y
  attribute \src "initiator.v:72"
  wire $logic_and$initiator.v:72$66_Y
  attribute \src "initiator.v:72"
  wire $logic_and$initiator.v:72$67_Y
  attribute \src "initiator.v:72"
  wire $logic_and$initiator.v:72$69_Y
  attribute \src "initiator.v:80"
  wire $logic_and$initiator.v:80$73_Y
  attribute \src "initiator.v:80"
  wire $logic_and$initiator.v:80$74_Y
  attribute \src "initiator.v:53"
  wire $logic_or$initiator.v:53$29_Y
  attribute \src "initiator.v:60"
  wire $logic_or$initiator.v:60$50_Y
  attribute \src "initiator.v:56"
  wire width 32 $memrd$\memory$initiator.v:56$35_DATA
  attribute \src "initiator.v:56"
  wire width 32 $memrd$\memory$initiator.v:56$39_DATA
  attribute \src "initiator.v:66"
  wire width 32 $memrd$\memory$initiator.v:66$57_DATA
  attribute \src "initiator.v:67"
  wire width 32 $memrd$\memory$initiator.v:67$58_DATA
  attribute \src "initiator.v:68"
  wire width 32 $memrd$\memory$initiator.v:68$59_DATA
  attribute \src "initiator.v:69"
  wire width 32 $memrd$\memory$initiator.v:69$60_DATA
  attribute \src "initiator.v:12"
  wire width 32 $memwr$\memory$initiator.v:12$1_ADDR
  attribute \src "initiator.v:12"
  wire width 32 $memwr$\memory$initiator.v:12$1_DATA
  attribute \src "initiator.v:12"
  wire width 32 $memwr$\memory$initiator.v:12$1_EN
  attribute \src "initiator.v:14"
  wire width 3 $memwr$\memory$initiator.v:14$2_ADDR
  attribute \src "initiator.v:14"
  wire width 32 $memwr$\memory$initiator.v:14$2_DATA
  attribute \src "initiator.v:14"
  wire width 32 $memwr$\memory$initiator.v:14$2_EN
  attribute \src "initiator.v:73"
  wire width 3 $memwr$\memory$initiator.v:73$3_ADDR
  attribute \src "initiator.v:73"
  wire width 32 $memwr$\memory$initiator.v:73$3_DATA
  attribute \src "initiator.v:73"
  wire width 32 $memwr$\memory$initiator.v:73$3_EN
  attribute \src "initiator.v:53"
  wire $ne$initiator.v:53$25_Y
  attribute \src "initiator.v:39"
  wire $not$initiator.v:39$19_Y
  attribute \src "initiator.v:30"
  wire width 32 $sub$initiator.v:30$16_Y
  attribute \src "initiator.v:56"
  wire width 32 $sub$initiator.v:56$40_Y
  attribute \src "initiator.v:39"
  wire width 32 $ternary$initiator.v:39$21_Y
  attribute \src "initiator.v:53"
  wire width 32 $ternary$initiator.v:53$30_Y
  attribute \src "initiator.v:53"
  wire width 32 $ternary$initiator.v:53$32_Y
  attribute \src "initiator.v:56"
  wire width 32 $ternary$initiator.v:56$41_Y
  attribute \src "initiator.v:56"
  wire width 32 $ternary$initiator.v:56$42_Y
  attribute \src "initiator.v:57"
  wire width 4 $ternary$initiator.v:57$46_Y
  attribute \src "initiator.v:57"
  wire width 4 $ternary$initiator.v:57$47_Y
  attribute \src "initiator.v:60"
  wire width 32 $ternary$initiator.v:60$55_Y
  attribute \src "initiator.v:60"
  wire width 32 $ternary$initiator.v:60$56_Y
  attribute \src "initiator.v:3"
  wire width 32 inout 7 \AD
  attribute \src "initiator.v:2"
  wire width 4 input 2 \BE
  attribute \src "initiator.v:3"
  wire width 4 output 8 \C_BE
  attribute \src "initiator.v:38"
  wire \bus_is_mine
  attribute \src "initiator.v:9"
  wire width 4 \byte_enable
  attribute \src "initiator.v:3"
  wire input 6 \clk
  attribute \src "initiator.v:8"
  wire width 4 \command
  attribute \src "initiator.v:24"
  wire width 2 \counter
  attribute \src "initiator.v:2"
  wire width 2 input 1 \devaddress
  attribute \src "initiator.v:5"
  wire input 13 \fcount
  attribute \src "initiator.v:5"
  wire input 14 \fend_count
  attribute \src "initiator.v:5"
  wire input 16 \ffinished
  attribute \src "initiator.v:2"
  wire input 3 \force_req
  attribute \src "initiator.v:3"
  wire output 9 \frame
  attribute \src "initiator.v:5"
  wire input 15 \freq_pending
  attribute \src "initiator.v:5"
  wire input 17 \fvalid
  attribute \src "initiator.v:3"
  wire output 10 \irdy
  attribute \src "initiator.v:65"
  wire width 32 \mem1
  attribute \src "initiator.v:65"
  wire width 32 \mem2
  attribute \src "initiator.v:65"
  wire width 32 \mem3
  attribute \src "initiator.v:65"
  wire width 32 \mem4
  attribute \src "initiator.v:63"
  wire width 3 \mp
  attribute \src "initiator.v:2"
  wire input 4 \rd_wr
  attribute \src "initiator.v:4"
  wire output 11 \req
  attribute \src "initiator.v:5"
  wire width 3 input 12 \state
  attribute \src "initiator.v:2"
  wire width 32 input 5 \write_data
  attribute \src "initiator.v:64"
  memory width 32 size 8 \memory
  attribute \src "initiator.v:27"
  cell $add $add$initiator.v:27$12
    parameter \A_SIGNED 0
    parameter \A_WIDTH 2
    parameter \B_SIGNED 0
    parameter \B_WIDTH 32
    parameter \Y_WIDTH 32
    connect \A \counter
    connect \B 1
    connect \Y $add$initiator.v:27$12_Y
  end
  attribute \src "initiator.v:81"
  cell $add $add$initiator.v:81$75
    parameter \A_SIGNED 0
    parameter \A_WIDTH 3
    parameter \B_SIGNED 0
    parameter \B_WIDTH 32
    parameter \Y_WIDTH 32
    connect \A \mp
    connect \B 1
    connect \Y $add$initiator.v:81$75_Y
  end
  attribute \src "initiator.v:29"
  cell $eq $eq$initiator.v:29$13
    parameter \A_SIGNED 0
    parameter \A_WIDTH 3
    parameter \B_SIGNED 0
    parameter \B_WIDTH 3
    parameter \Y_WIDTH 1
    connect \A \state
    connect \B 3'011
    connect \Y $eq$initiator.v:29$13_Y
  end
  attribute \src "initiator.v:44"
  cell $eq $eq$initiator.v:44$23
    parameter \A_SIGNED 0
    parameter \A_WIDTH 3
    parameter \B_SIGNED 0
    parameter \B_WIDTH 3
    parameter \Y_WIDTH 1
    connect \A \state
    connect \B 3'001
    connect \Y $eq$initiator.v:44$23_Y
  end
  attribute \src "initiator.v:53"
  cell $eq $eq$initiator.v:53$27
    parameter \A_SIGNED 0
    parameter \A_WIDTH 3
    parameter \B_SIGNED 0
    parameter \B_WIDTH 3
    parameter \Y_WIDTH 1
    connect \A \state
    connect \B 3'001
    connect \Y $eq$initiator.v:53$27_Y
  end
  attribute \src "initiator.v:56"
  cell $eq $eq$initiator.v:56$33
    parameter \A_SIGNED 0
    parameter \A_WIDTH 3
    parameter \B_SIGNED 0
    parameter \B_WIDTH 3
    parameter \Y_WIDTH 1
    connect \A \state
    connect \B 3'001
    connect \Y $eq$initiator.v:56$33_Y
  end
  attribute \src "initiator.v:56"
  cell $eq $eq$initiator.v:56$36
    parameter \A_SIGNED 0
    parameter \A_WIDTH 4
    parameter \B_SIGNED 0
    parameter \B_WIDTH 32
    parameter \Y_WIDTH 1
    connect \A \command
    connect \B 0
    connect \Y $eq$initiator.v:56$36_Y
  end
  attribute \src "initiator.v:56"
  cell $eq $eq$initiator.v:56$37
    parameter \A_SIGNED 0
    parameter \A_WIDTH 3
    parameter \B_SIGNED 0
    parameter \B_WIDTH 3
    parameter \Y_WIDTH 1
    connect \A \state
    connect \B 3'011
    connect \Y $eq$initiator.v:56$37_Y
  end
  attribute \src "initiator.v:57"
  cell $eq $eq$initiator.v:57$43
    parameter \A_SIGNED 0
    parameter \A_WIDTH 3
    parameter \B_SIGNED 0
    parameter \B_WIDTH 3
    parameter \Y_WIDTH 1
    connect \A \state
    connect \B 3'001
    connect \Y $eq$initiator.v:57$43_Y
  end
  attribute \src "initiator.v:57"
  cell $eq $eq$initiator.v:57$45
    parameter \A_SIGNED 0
    parameter \A_WIDTH 3
    parameter \B_SIGNED 0
    parameter \B_WIDTH 3
    parameter \Y_WIDTH 1
    connect \A \state
    connect \B 3'011
    connect \Y $eq$initiator.v:57$45_Y
  end
  attribute \src "initiator.v:60"
  cell $eq $eq$initiator.v:60$48
    parameter \A_SIGNED 0
    parameter \A_WIDTH 3
    parameter \B_SIGNED 0
    parameter \B_WIDTH 3
    parameter \Y_WIDTH 1
    connect \A \state
    connect \B 3'010
    connect \Y $eq$initiator.v:60$48_Y
  end
  attribute \src "initiator.v:60"
  cell $eq $eq$initiator.v:60$49
    parameter \A_SIGNED 0
    parameter \A_WIDTH 3
    parameter \B_SIGNED 0
    parameter \B_WIDTH 3
    parameter \Y_WIDTH 1
    connect \A \state
    connect \B 3'011
    connect \Y $eq$initiator.v:60$49_Y
  end
  attribute \src "initiator.v:60"
  cell $eq $eq$initiator.v:60$52
    parameter \A_SIGNED 0
    parameter \A_WIDTH 3
    parameter \B_SIGNED 0
    parameter \B_WIDTH 3
    parameter \Y_WIDTH 1
    connect \A \state
    connect \B 3'100
    connect \Y $eq$initiator.v:60$52_Y
  end
  attribute \src "initiator.v:72"
  cell $eq $eq$initiator.v:72$65
    parameter \A_SIGNED 0
    parameter \A_WIDTH 3
    parameter \B_SIGNED 0
    parameter \B_WIDTH 3
    parameter \Y_WIDTH 1
    connect \A \state
    connect \B 3'011
    connect \Y $eq$initiator.v:72$65_Y
  end
  attribute \src "initiator.v:72"
  cell $eq $eq$initiator.v:72$68
    parameter \A_SIGNED 0
    parameter \A_WIDTH 4
    parameter \B_SIGNED 0
    parameter \B_WIDTH 32
    parameter \Y_WIDTH 1
    connect \A \command
    connect \B 1
    connect \Y $eq$initiator.v:72$68_Y
  end
  attribute \src "initiator.v:75"
  cell $eq $eq$initiator.v:75$70
    parameter \A_SIGNED 0
    parameter \A_WIDTH 3
    parameter \B_SIGNED 0
    parameter \B_WIDTH 3
    parameter \Y_WIDTH 1
    connect \A \state
    connect \B 3'000
    connect \Y $eq$initiator.v:75$70_Y
  end
  attribute \src "initiator.v:80"
  cell $eq $eq$initiator.v:80$72
    parameter \A_SIGNED 0
    parameter \A_WIDTH 3
    parameter \B_SIGNED 0
    parameter \B_WIDTH 3
    parameter \Y_WIDTH 1
    connect \A \state
    connect \B 3'011
    connect \Y $eq$initiator.v:80$72_Y
  end
  attribute \src "initiator.v:53"
  cell $pos $extend$initiator.v:53$31
    parameter \A_SIGNED 0
    parameter \A_WIDTH 1
    parameter \Y_WIDTH 32
    connect \A 1'z
    connect \Y $extend$initiator.v:53$31_Y
  end
  attribute \src "initiator.v:60"
  cell $pos $extend$initiator.v:60$54
    parameter \A_SIGNED 0
    parameter \A_WIDTH 1
    parameter \Y_WIDTH 32
    connect \A 1'z
    connect \Y $extend$initiator.v:60$54_Y
  end
  attribute \src "initiator.v:53"
  cell $gt $gt$initiator.v:53$28
    parameter \A_SIGNED 0
    parameter \A_WIDTH 2
    parameter \B_SIGNED 0
    parameter \B_WIDTH 32
    parameter \Y_WIDTH 1
    connect \A \counter
    connect \B 1
    connect \Y $gt$initiator.v:53$28_Y
  end
  attribute \src "initiator.v:29"
  cell $logic_and $logic_and$initiator.v:29$14
    parameter \A_SIGNED 0
    parameter \A_WIDTH 1
    parameter \B_SIGNED 0
    parameter \B_WIDTH 1
    parameter \Y_WIDTH 1
    connect \A $eq$initiator.v:29$13_Y
    connect \B \fvalid
    connect \Y $logic_and$initiator.v:29$14_Y
  end
  attribute \src "initiator.v:29"
  cell $logic_and $logic_and$initiator.v:29$15
    parameter \A_SIGNED 0
    parameter \A_WIDTH 1
    parameter \B_SIGNED 0
    parameter \B_WIDTH 1
    parameter \Y_WIDTH 1
    connect \A $logic_and$initiator.v:29$14_Y
    connect \B \bus_is_mine
    connect \Y $logic_and$initiator.v:29$15_Y
  end
  attribute \src "initiator.v:39"
  cell $logic_and $logic_and$initiator.v:39$18
    parameter \A_SIGNED 0
    parameter \A_WIDTH 1
    parameter \B_SIGNED 0
    parameter \B_WIDTH 2
    parameter \Y_WIDTH 1
    connect \A \fend_count
    connect \B \counter
    connect \Y $logic_and$initiator.v:39$18_Y
  end
  attribute \src "initiator.v:39"
  cell $logic_and $logic_and$initiator.v:39$20
    parameter \A_SIGNED 0
    parameter \A_WIDTH 1
    parameter \B_SIGNED 0
    parameter \B_WIDTH 1
    parameter \Y_WIDTH 1
    connect \A $logic_and$initiator.v:39$18_Y
    connect \B $not$initiator.v:39$19_Y
    connect \Y $logic_and$initiator.v:39$20_Y
  end
  attribute \src "initiator.v:47"
  cell $logic_and $logic_and$initiator.v:47$24
    parameter \A_SIGNED 0
    parameter \A_WIDTH 1
    parameter \B_SIGNED 0
    parameter \B_WIDTH 1
    parameter \Y_WIDTH 1
    connect \A $2\bus_is_mine[0:0]
    connect \B \ffinished
    connect \Y $logic_and$initiator.v:47$24_Y
  end
  attribute \src "initiator.v:53"
  cell $logic_and $logic_and$initiator.v:53$26
    parameter \A_SIGNED 0
    parameter \A_WIDTH 1
    parameter \B_SIGNED 0
    parameter \B_WIDTH 1
    parameter \Y_WIDTH 1
    connect \A \bus_is_mine
    connect \B $ne$initiator.v:53$25_Y
    connect \Y $logic_and$initiator.v:53$26_Y
  end
  attribute \src "initiator.v:56"
  cell $logic_and $logic_and$initiator.v:56$34
    parameter \A_SIGNED 0
    parameter \A_WIDTH 1
    parameter \B_SIGNED 0
    parameter \B_WIDTH 1
    parameter \Y_WIDTH 1
    connect \A $eq$initiator.v:56$33_Y
    connect \B \bus_is_mine
    connect \Y $logic_and$initiator.v:56$34_Y
  end
  attribute \src "initiator.v:56"
  cell $logic_and $logic_and$initiator.v:56$38
    parameter \A_SIGNED 0
    parameter \A_WIDTH 1
    parameter \B_SIGNED 0
    parameter \B_WIDTH 1
    parameter \Y_WIDTH 1
    connect \A $eq$initiator.v:56$36_Y
    connect \B $eq$initiator.v:56$37_Y
    connect \Y $logic_and$initiator.v:56$38_Y
  end
  attribute \src "initiator.v:57"
  cell $logic_and $logic_and$initiator.v:57$44
    parameter \A_SIGNED 0
    parameter \A_WIDTH 1
    parameter \B_SIGNED 0
    parameter \B_WIDTH 1
    parameter \Y_WIDTH 1
    connect \A $eq$initiator.v:57$43_Y
    connect \B \bus_is_mine
    connect \Y $logic_and$initiator.v:57$44_Y
  end
  attribute \src "initiator.v:60"
  cell $logic_and $logic_and$initiator.v:60$51
    parameter \A_SIGNED 0
    parameter \A_WIDTH 1
    parameter \B_SIGNED 0
    parameter \B_WIDTH 1
    parameter \Y_WIDTH 1
    connect \A \bus_is_mine
    connect \B $logic_or$initiator.v:60$50_Y
    connect \Y $logic_and$initiator.v:60$51_Y
  end
  attribute \src "initiator.v:60"
  cell $logic_and $logic_and$initiator.v:60$53
    parameter \A_SIGNED 0
    parameter \A_WIDTH 1
    parameter \B_SIGNED 0
    parameter \B_WIDTH 1
    parameter \Y_WIDTH 1
    connect \A \bus_is_mine
    connect \B $eq$initiator.v:60$52_Y
    connect \Y $logic_and$initiator.v:60$53_Y
  end
  attribute \src "initiator.v:72"
  cell $logic_and $logic_and$initiator.v:72$66
    parameter \A_SIGNED 0
    parameter \A_WIDTH 1
    parameter \B_SIGNED 0
    parameter \B_WIDTH 1
    parameter \Y_WIDTH 1
    connect \A $eq$initiator.v:72$65_Y
    connect \B \fvalid
    connect \Y $logic_and$initiator.v:72$66_Y
  end
  attribute \src "initiator.v:72"
  cell $logic_and $logic_and$initiator.v:72$67
    parameter \A_SIGNED 0
    parameter \A_WIDTH 1
    parameter \B_SIGNED 0
    parameter \B_WIDTH 1
    parameter \Y_WIDTH 1
    connect \A \bus_is_mine
    connect \B $logic_and$initiator.v:72$66_Y
    connect \Y $logic_and$initiator.v:72$67_Y
  end
  attribute \src "initiator.v:72"
  cell $logic_and $logic_and$initiator.v:72$69
    parameter \A_SIGNED 0
    parameter \A_WIDTH 1
    parameter \B_SIGNED 0
    parameter \B_WIDTH 1
    parameter \Y_WIDTH 1
    connect \A $logic_and$initiator.v:72$67_Y
    connect \B $eq$initiator.v:72$68_Y
    connect \Y $logic_and$initiator.v:72$69_Y
  end
  attribute \src "initiator.v:80"
  cell $logic_and $logic_and$initiator.v:80$73
    parameter \A_SIGNED 0
    parameter \A_WIDTH 1
    parameter \B_SIGNED 0
    parameter \B_WIDTH 1
    parameter \Y_WIDTH 1
    connect \A $eq$initiator.v:80$72_Y
    connect \B \fvalid
    connect \Y $logic_and$initiator.v:80$73_Y
  end
  attribute \src "initiator.v:80"
  cell $logic_and $logic_and$initiator.v:80$74
    parameter \A_SIGNED 0
    parameter \A_WIDTH 1
    parameter \B_SIGNED 0
    parameter \B_WIDTH 1
    parameter \Y_WIDTH 1
    connect \A \bus_is_mine
    connect \B $logic_and$initiator.v:80$73_Y
    connect \Y $logic_and$initiator.v:80$74_Y
  end
  attribute \src "initiator.v:53"
  cell $logic_or $logic_or$initiator.v:53$29
    parameter \A_SIGNED 0
    parameter \A_WIDTH 1
    parameter \B_SIGNED 0
    parameter \B_WIDTH 1
    parameter \Y_WIDTH 1
    connect \A $eq$initiator.v:53$27_Y
    connect \B $gt$initiator.v:53$28_Y
    connect \Y $logic_or$initiator.v:53$29_Y
  end
  attribute \src "initiator.v:60"
  cell $logic_or $logic_or$initiator.v:60$50
    parameter \A_SIGNED 0
    parameter \A_WIDTH 1
    parameter \B_SIGNED 0
    parameter \B_WIDTH 1
    parameter \Y_WIDTH 1
    connect \A $eq$initiator.v:60$48_Y
    connect \B $eq$initiator.v:60$49_Y
    connect \Y $logic_or$initiator.v:60$50_Y
  end
  attribute \src "initiator.v:56"
  cell $memrd $memrd$\memory$initiator.v:56$35
    parameter \ABITS 32
    parameter \CLK_ENABLE 0
    parameter \CLK_POLARITY 0
    parameter \MEMID "\\memory"
    parameter \TRANSPARENT 0
    parameter \WIDTH 32
    connect \ADDR 7
    connect \CLK 1'x
    connect \DATA $memrd$\memory$initiator.v:56$35_DATA
    connect \EN 1'x
  end
  attribute \src "initiator.v:56"
  cell $memrd $memrd$\memory$initiator.v:56$39
    parameter \ABITS 32
    parameter \CLK_ENABLE 0
    parameter \CLK_POLARITY 0
    parameter \MEMID "\\memory"
    parameter \TRANSPARENT 0
    parameter \WIDTH 32
    connect \ADDR $sub$initiator.v:56$40_Y
    connect \CLK 1'x
    connect \DATA $memrd$\memory$initiator.v:56$39_DATA
    connect \EN 1'x
  end
  attribute \src "initiator.v:66"
  cell $memrd $memrd$\memory$initiator.v:66$57
    parameter \ABITS 32
    parameter \CLK_ENABLE 0
    parameter \CLK_POLARITY 0
    parameter \MEMID "\\memory"
    parameter \TRANSPARENT 0
    parameter \WIDTH 32
    connect \ADDR 0
    connect \CLK 1'x
    connect \DATA $memrd$\memory$initiator.v:66$57_DATA
    connect \EN 1'x
  end
  attribute \src "initiator.v:67"
  cell $memrd $memrd$\memory$initiator.v:67$58
    parameter \ABITS 32
    parameter \CLK_ENABLE 0
    parameter \CLK_POLARITY 0
    parameter \MEMID "\\memory"
    parameter \TRANSPARENT 0
    parameter \WIDTH 32
    connect \ADDR 1
    connect \CLK 1'x
    connect \DATA $memrd$\memory$initiator.v:67$58_DATA
    connect \EN 1'x
  end
  attribute \src "initiator.v:68"
  cell $memrd $memrd$\memory$initiator.v:68$59
    parameter \ABITS 32
    parameter \CLK_ENABLE 0
    parameter \CLK_POLARITY 0
    parameter \MEMID "\\memory"
    parameter \TRANSPARENT 0
    parameter \WIDTH 32
    connect \ADDR 2
    connect \CLK 1'x
    connect \DATA $memrd$\memory$initiator.v:68$59_DATA
    connect \EN 1'x
  end
  attribute \src "initiator.v:69"
  cell $memrd $memrd$\memory$initiator.v:69$60
    parameter \ABITS 32
    parameter \CLK_ENABLE 0
    parameter \CLK_POLARITY 0
    parameter \MEMID "\\memory"
    parameter \TRANSPARENT 0
    parameter \WIDTH 32
    connect \ADDR 3
    connect \CLK 1'x
    connect \DATA $memrd$\memory$initiator.v:69$60_DATA
    connect \EN 1'x
  end
  attribute \src "initiator.v:12"
  cell $memwr $memwr$\memory$initiator.v:12$76
    parameter \ABITS 32
    parameter \CLK_ENABLE 0
    parameter \CLK_POLARITY 0
    parameter \MEMID "\\memory"
    parameter \PRIORITY 76
    parameter \WIDTH 32
    connect \ADDR $memwr$\memory$initiator.v:12$1_ADDR
    connect \CLK 1'x
    connect \DATA $memwr$\memory$initiator.v:12$1_DATA
    connect \EN $memwr$\memory$initiator.v:12$1_EN
  end
  attribute \src "initiator.v:14"
  cell $memwr $memwr$\memory$initiator.v:14$77
    parameter \ABITS 3
    parameter \CLK_ENABLE 0
    parameter \CLK_POLARITY 0
    parameter \MEMID "\\memory"
    parameter \PRIORITY 77
    parameter \WIDTH 32
    connect \ADDR $memwr$\memory$initiator.v:14$2_ADDR
    connect \CLK 1'x
    connect \DATA $memwr$\memory$initiator.v:14$2_DATA
    connect \EN $memwr$\memory$initiator.v:14$2_EN
  end
  attribute \src "initiator.v:73"
  cell $memwr $memwr$\memory$initiator.v:73$78
    parameter \ABITS 3
    parameter \CLK_ENABLE 0
    parameter \CLK_POLARITY 0
    parameter \MEMID "\\memory"
    parameter \PRIORITY 78
    parameter \WIDTH 32
    connect \ADDR $memwr$\memory$initiator.v:73$3_ADDR
    connect \CLK 1'x
    connect \DATA $memwr$\memory$initiator.v:73$3_DATA
    connect \EN $memwr$\memory$initiator.v:73$3_EN
  end
  attribute \src "initiator.v:53"
  cell $ne $ne$initiator.v:53$25
    parameter \A_SIGNED 0
    parameter \A_WIDTH 3
    parameter \B_SIGNED 0
    parameter \B_WIDTH 3
    parameter \Y_WIDTH 1
    connect \A \state
    connect \B 3'100
    connect \Y $ne$initiator.v:53$25_Y
  end
  attribute \src "initiator.v:39"
  cell $not $not$initiator.v:39$19
    parameter \A_SIGNED 0
    parameter \A_WIDTH 1
    parameter \Y_WIDTH 1
    connect \A \bus_is_mine
    connect \Y $not$initiator.v:39$19_Y
  end
  attribute \src "initiator.v:30"
  cell $sub $sub$initiator.v:30$16
    parameter \A_SIGNED 0
    parameter \A_WIDTH 2
    parameter \B_SIGNED 0
    parameter \B_WIDTH 32
    parameter \Y_WIDTH 32
    connect \A $1\counter[1:0]
    connect \B 1
    connect \Y $sub$initiator.v:30$16_Y
  end
  attribute \src "initiator.v:56"
  cell $sub $sub$initiator.v:56$40
    parameter \A_SIGNED 0
    parameter \A_WIDTH 2
    parameter \B_SIGNED 0
    parameter \B_WIDTH 32
    parameter \Y_WIDTH 32
    connect \A \counter
    connect \B 1
    connect \Y $sub$initiator.v:56$40_Y
  end
  attribute \src "initiator.v:39"
  cell $mux $ternary$initiator.v:39$21
    parameter \WIDTH 32
    connect \A 1
    connect \B 0
    connect \S $logic_and$initiator.v:39$20_Y
    connect \Y $ternary$initiator.v:39$21_Y
  end
  attribute \src "initiator.v:53"
  cell $mux $ternary$initiator.v:53$30
    parameter \WIDTH 32
    connect \A 1
    connect \B 0
    connect \S $logic_or$initiator.v:53$29_Y
    connect \Y $ternary$initiator.v:53$30_Y
  end
  attribute \src "initiator.v:53"
  cell $mux $ternary$initiator.v:53$32
    parameter \WIDTH 32
    connect \A $extend$initiator.v:53$31_Y
    connect \B $ternary$initiator.v:53$30_Y
    connect \S $logic_and$initiator.v:53$26_Y
    connect \Y $ternary$initiator.v:53$32_Y
  end
  attribute \src "initiator.v:56"
  cell $mux $ternary$initiator.v:56$41
    parameter \WIDTH 32
    connect \A 32'zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz
    connect \B $memrd$\memory$initiator.v:56$39_DATA
    connect \S $logic_and$initiator.v:56$38_Y
    connect \Y $ternary$initiator.v:56$41_Y
  end
  attribute \src "initiator.v:56"
  cell $mux $ternary$initiator.v:56$42
    parameter \WIDTH 32
    connect \A $ternary$initiator.v:56$41_Y
    connect \B $memrd$\memory$initiator.v:56$35_DATA
    connect \S $logic_and$initiator.v:56$34_Y
    connect \Y $ternary$initiator.v:56$42_Y
  end
  attribute \src "initiator.v:57"
  cell $mux $ternary$initiator.v:57$46
    parameter \WIDTH 4
    connect \A 4'zzzz
    connect \B \byte_enable
    connect \S $eq$initiator.v:57$45_Y
    connect \Y $ternary$initiator.v:57$46_Y
  end
  attribute \src "initiator.v:57"
  cell $mux $ternary$initiator.v:57$47
    parameter \WIDTH 4
    connect \A $ternary$initiator.v:57$46_Y
    connect \B \command
    connect \S $logic_and$initiator.v:57$44_Y
    connect \Y $ternary$initiator.v:57$47_Y
  end
  attribute \src "initiator.v:60"
  cell $mux $ternary$initiator.v:60$55
    parameter \WIDTH 32
    connect \A $extend$initiator.v:60$54_Y
    connect \B 1
    connect \S $logic_and$initiator.v:60$53_Y
    connect \Y $ternary$initiator.v:60$55_Y
  end
  attribute \src "initiator.v:60"
  cell $mux $ternary$initiator.v:60$56
    parameter \WIDTH 32
    connect \A $ternary$initiator.v:60$55_Y
    connect \B 0
    connect \S $logic_and$initiator.v:60$51_Y
    connect \Y $ternary$initiator.v:60$56_Y
  end
  attribute \src "initiator.v:10"
  process $proc$initiator.v:10$4
    assign $0\byte_enable[3:0] \byte_enable
    assign $0\command[3:0] \command
    assign { } { }
    assign { } { }
    assign { } { }
    assign { } { }
    assign { } { }
    assign { } { }
    assign $0$memwr$\memory$initiator.v:14$2_ADDR[2:0]$8 3'xxx
    assign $0$memwr$\memory$initiator.v:14$2_DATA[31:0]$9 32'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    assign $0$memwr$\memory$initiator.v:14$2_EN[31:0]$10 0
    assign $0$memwr$\memory$initiator.v:12$1_ADDR[31:0]$5 32'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    assign $0$memwr$\memory$initiator.v:12$1_DATA[31:0]$6 32'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    assign $0$memwr$\memory$initiator.v:12$1_EN[31:0]$7 0
    attribute \src "initiator.v:11"
    switch \force_req
      case 1'1
        assign $0$memwr$\memory$initiator.v:12$1_ADDR[31:0]$5 7
        assign $0$memwr$\memory$initiator.v:12$1_DATA[31:0]$6 { 30'000000000000000000000000000000 \devaddress }
        assign $0$memwr$\memory$initiator.v:12$1_EN[31:0]$7 32'11111111111111111111111111111111
        assign $0\command[3:0] { 3'000 \rd_wr }
        assign $0$memwr$\memory$initiator.v:14$2_ADDR[2:0]$8 { 1'0 \counter }
        assign $0$memwr$\memory$initiator.v:14$2_DATA[31:0]$9 \write_data
        assign $0$memwr$\memory$initiator.v:14$2_EN[31:0]$10 32'11111111111111111111111111111111
        assign $0\byte_enable[3:0] \BE
      case 
    end
    sync posedge \clk
      update \byte_enable $0\byte_enable[3:0]
      update \command $0\command[3:0]
      update $memwr$\memory$initiator.v:12$1_ADDR $0$memwr$\memory$initiator.v:12$1_ADDR[31:0]$5
      update $memwr$\memory$initiator.v:12$1_DATA $0$memwr$\memory$initiator.v:12$1_DATA[31:0]$6
      update $memwr$\memory$initiator.v:12$1_EN $0$memwr$\memory$initiator.v:12$1_EN[31:0]$7
      update $memwr$\memory$initiator.v:14$2_ADDR $0$memwr$\memory$initiator.v:14$2_ADDR[2:0]$8
      update $memwr$\memory$initiator.v:14$2_DATA $0$memwr$\memory$initiator.v:14$2_DATA[31:0]$9
      update $memwr$\memory$initiator.v:14$2_EN $0$memwr$\memory$initiator.v:14$2_EN[31:0]$10
  end
  attribute \src "initiator.v:25"
  process $proc$initiator.v:25$11
    assign { } { }
    assign { } { }
    assign $0\counter[1:0] $2\counter[1:0]
    attribute \src "initiator.v:26"
    switch \fcount
      case 1'1
        assign { } { }
        assign $1\counter[1:0] $add$initiator.v:27$12_Y [1:0]
      case 
        assign $1\counter[1:0] \counter
    end
    attribute \src "initiator.v:29"
    switch $logic_and$initiator.v:29$15_Y
      case 1'1
        assign { } { }
        assign $2\counter[1:0] $sub$initiator.v:30$16_Y [1:0]
      case 
        assign $2\counter[1:0] $1\counter[1:0]
    end
    sync negedge \clk
      update \counter $0\counter[1:0]
  end
  attribute \src "initiator.v:33"
  process $proc$initiator.v:33$17
    assign { } { }
    assign $3\counter[1:0] 2'00
    sync posedge \force_req
      update \counter $3\counter[1:0]
  end
  attribute \src "initiator.v:40"
  process $proc$initiator.v:40$22
    assign { } { }
    assign { } { }
    assign { } { }
    assign $0\bus_is_mine[0:0] $3\bus_is_mine[0:0]
    attribute \src "initiator.v:41"
    switch \fcount
      case 1'1
        assign { } { }
        assign $1\bus_is_mine[0:0] 1'0
      case 
        assign $1\bus_is_mine[0:0] \bus_is_mine
    end
    attribute \src "initiator.v:44"
    switch $eq$initiator.v:44$23_Y
      case 1'1
        assign { } { }
        assign $2\bus_is_mine[0:0] 1'1
      case 
        assign $2\bus_is_mine[0:0] $1\bus_is_mine[0:0]
    end
    attribute \src "initiator.v:47"
    switch $logic_and$initiator.v:47$24_Y
      case 1'1
        assign { } { }
        assign $3\bus_is_mine[0:0] 1'0
      case 
        assign $3\bus_is_mine[0:0] $2\bus_is_mine[0:0]
    end
    sync always
      update \bus_is_mine $0\bus_is_mine[0:0]
  end
  attribute \src "initiator.v:71"
  process $proc$initiator.v:71$61
    assign $0\mp[2:0] \mp
    assign { } { }
    assign { } { }
    assign { } { }
    assign $0$memwr$\memory$initiator.v:73$3_ADDR[2:0]$62 3'xxx
    assign $0$memwr$\memory$initiator.v:73$3_DATA[31:0]$63 32'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    assign $0$memwr$\memory$initiator.v:73$3_EN[31:0]$64 0
    attribute \src "initiator.v:72"
    switch $logic_and$initiator.v:72$69_Y
      case 1'1
        assign $0$memwr$\memory$initiator.v:73$3_ADDR[2:0]$62 \mp
        assign $0$memwr$\memory$initiator.v:73$3_DATA[31:0]$63 \AD
        assign $0$memwr$\memory$initiator.v:73$3_EN[31:0]$64 32'11111111111111111111111111111111
      case 
    end
    attribute \src "initiator.v:75"
    switch $eq$initiator.v:75$70_Y
      case 1'1
        assign $0\mp[2:0] 3'000
      case 
    end
    sync posedge \clk
      update \mp $0\mp[2:0]
      update $memwr$\memory$initiator.v:73$3_ADDR $0$memwr$\memory$initiator.v:73$3_ADDR[2:0]$62
      update $memwr$\memory$initiator.v:73$3_DATA $0$memwr$\memory$initiator.v:73$3_DATA[31:0]$63
      update $memwr$\memory$initiator.v:73$3_EN $0$memwr$\memory$initiator.v:73$3_EN[31:0]$64
  end
  attribute \src "initiator.v:79"
  process $proc$initiator.v:79$71
    assign $1\mp[2:0] \mp
    attribute \src "initiator.v:80"
    switch $logic_and$initiator.v:80$74_Y
      case 1'1
        assign $1\mp[2:0] $add$initiator.v:81$75_Y [2:0]
      case 
    end
    sync negedge \clk
      update \mp $1\mp[2:0]
  end
  connect \req $ternary$initiator.v:39$21_Y [0]
  connect \frame $ternary$initiator.v:53$32_Y [0]
  connect \AD $ternary$initiator.v:56$42_Y
  connect \C_BE $ternary$initiator.v:57$47_Y
  connect \irdy $ternary$initiator.v:60$56_Y [0]
  connect \mem1 $memrd$\memory$initiator.v:66$57_DATA
  connect \mem2 $memrd$\memory$initiator.v:67$58_DATA
  connect \mem3 $memrd$\memory$initiator.v:68$59_DATA
  connect \mem4 $memrd$\memory$initiator.v:69$60_DATA
end
attribute \cells_not_processed 1
attribute \src "state_machine2.v:1"
module \State_Machine
  parameter \address
  parameter \data
  parameter \finish
  parameter \idle
  parameter \turnaround
  attribute \src "state_machine2.v:35"
  wire $0\fcount[0:0]
  attribute \src "state_machine2.v:35"
  wire $0\fend_count[0:0]
  attribute \src "state_machine2.v:35"
  wire $0\ffinished[0:0]
  attribute \src "state_machine2.v:35"
  wire $0\fgnt[0:0]
  attribute \src "state_machine2.v:35"
  wire $0\freq_pending[0:0]
  attribute \src "state_machine2.v:64"
  wire $0\fvalid[0:0]
  attribute \src "state_machine2.v:64"
  wire width 3 $0\next_state[2:0]
  attribute \src "state_machine2.v:35"
  wire width 3 $0\state[2:0]
  attribute \src "state_machine2.v:64"
  wire $1\fvalid[0:0]
  attribute \src "state_machine2.v:64"
  wire width 3 $1\next_state[2:0]
  attribute \src "state_machine2.v:64"
  wire $2\fvalid[0:0]
  attribute \src "state_machine2.v:64"
  wire width 3 $2\next_state[2:0]
  attribute \src "state_machine2.v:64"
  wire width 3 $3\next_state[2:0]
  attribute \src "state_machine2.v:64"
  wire width 3 $4\next_state[2:0]
  attribute \src "state_machine2.v:64"
  wire width 3 $5\next_state[2:0]
  attribute \src "state_machine2.v:52"
  wire $eq$state_machine2.v:52$113_Y
  attribute \src "state_machine2.v:56"
  wire $eq$state_machine2.v:56$114_Y
  attribute \src "state_machine2.v:41"
  wire $logic_and$state_machine2.v:41$110_Y
  attribute \src "state_machine2.v:45"
  wire $logic_and$state_machine2.v:45$112_Y
  attribute \src "state_machine2.v:88"
  wire $logic_and$state_machine2.v:88$120_Y
  attribute \src "state_machine2.v:41"
  wire $logic_not$state_machine2.v:41$109_Y
  attribute \src "state_machine2.v:45"
  wire $logic_not$state_machine2.v:45$111_Y
  attribute \src "state_machine2.v:59"
  wire $logic_not$state_machine2.v:59$115_Y
  attribute \src "state_machine2.v:71"
  wire $logic_not$state_machine2.v:71$117_Y
  attribute \src "state_machine2.v:88"
  wire $logic_not$state_machine2.v:88$118_Y
  attribute \src "state_machine2.v:88"
  wire $logic_not$state_machine2.v:88$119_Y
  attribute \src "state_machine2.v:11"
  wire input 6 \clk
  attribute \src "state_machine2.v:11"
  wire input 4 \devsel
  attribute \src "state_machine2.v:27"
  wire output 11 \fcount
  attribute \src "state_machine2.v:27"
  wire output 12 \fend_count
  attribute \src "state_machine2.v:27"
  wire output 14 \ffinished
  attribute \src "state_machine2.v:33"
  wire \fgnt
  attribute \src "state_machine2.v:11"
  wire input 7 \force_req
  attribute \src "state_machine2.v:11"
  wire input 1 \frame
  attribute \src "state_machine2.v:27"
  wire output 13 \freq_pending
  attribute \src "state_machine2.v:27"
  wire output 15 \fvalid
  attribute \src "state_machine2.v:11"
  wire input 9 \gnt
  attribute \src "state_machine2.v:11"
  wire input 2 \irdy
  attribute \src "state_machine2.v:13"
  wire width 3 \next_state
  attribute \src "state_machine2.v:11"
  wire input 10 \rd_wr
  attribute \src "state_machine2.v:11"
  wire input 8 \req
  attribute \src "state_machine2.v:12"
  wire width 3 output 5 \state
  attribute \src "state_machine2.v:11"
  wire input 3 \trdy
  attribute \src "state_machine2.v:52"
  cell $eq $eq$state_machine2.v:52$113
    parameter \A_SIGNED 0
    parameter \A_WIDTH 3
    parameter \B_SIGNED 0
    parameter \B_WIDTH 3
    parameter \Y_WIDTH 1
    connect \A \state
    connect \B 3'001
    connect \Y $eq$state_machine2.v:52$113_Y
  end
  attribute \src "state_machine2.v:56"
  cell $eq $eq$state_machine2.v:56$114
    parameter \A_SIGNED 0
    parameter \A_WIDTH 3
    parameter \B_SIGNED 0
    parameter \B_WIDTH 3
    parameter \Y_WIDTH 1
    connect \A \state
    connect \B 3'100
    connect \Y $eq$state_machine2.v:56$114_Y
  end
  attribute \src "state_machine2.v:41"
  cell $logic_and $logic_and$state_machine2.v:41$110
    parameter \A_SIGNED 0
    parameter \A_WIDTH 1
    parameter \B_SIGNED 0
    parameter \B_WIDTH 1
    parameter \Y_WIDTH 1
    connect \A $logic_not$state_machine2.v:41$109_Y
    connect \B \fcount
    connect \Y $logic_and$state_machine2.v:41$110_Y
  end
  attribute \src "state_machine2.v:45"
  cell $logic_and $logic_and$state_machine2.v:45$112
    parameter \A_SIGNED 0
    parameter \A_WIDTH 1
    parameter \B_SIGNED 0
    parameter \B_WIDTH 1
    parameter \Y_WIDTH 1
    connect \A $logic_not$state_machine2.v:45$111_Y
    connect \B \gnt
    connect \Y $logic_and$state_machine2.v:45$112_Y
  end
  attribute \src "state_machine2.v:88"
  cell $logic_and $logic_and$state_machine2.v:88$120
    parameter \A_SIGNED 0
    parameter \A_WIDTH 1
    parameter \B_SIGNED 0
    parameter \B_WIDTH 1
    parameter \Y_WIDTH 1
    connect \A $logic_not$state_machine2.v:88$118_Y
    connect \B $logic_not$state_machine2.v:88$119_Y
    connect \Y $logic_and$state_machine2.v:88$120_Y
  end
  attribute \src "state_machine2.v:41"
  cell $logic_not $logic_not$state_machine2.v:41$109
    parameter \A_SIGNED 0
    parameter \A_WIDTH 1
    parameter \Y_WIDTH 1
    connect \A \force_req
    connect \Y $logic_not$state_machine2.v:41$109_Y
  end
  attribute \src "state_machine2.v:45"
  cell $logic_not $logic_not$state_machine2.v:45$111
    parameter \A_SIGNED 0
    parameter \A_WIDTH 1
    parameter \Y_WIDTH 1
    connect \A \req
    connect \Y $logic_not$state_machine2.v:45$111_Y
  end
  attribute \src "state_machine2.v:59"
  cell $logic_not $logic_not$state_machine2.v:59$115
    parameter \A_SIGNED 0
    parameter \A_WIDTH 1
    parameter \Y_WIDTH 1
    connect \A \gnt
    connect \Y $logic_not$state_machine2.v:59$115_Y
  end
  attribute \src "state_machine2.v:71"
  cell $logic_not $logic_not$state_machine2.v:71$117
    parameter \A_SIGNED 0
    parameter \A_WIDTH 1
    parameter \Y_WIDTH 1
    connect \A \frame
    connect \Y $logic_not$state_machine2.v:71$117_Y
  end
  attribute \src "state_machine2.v:88"
  cell $logic_not $logic_not$state_machine2.v:88$118
    parameter \A_SIGNED 0
    parameter \A_WIDTH 1
    parameter \Y_WIDTH 1
    connect \A \trdy
    connect \Y $logic_not$state_machine2.v:88$118_Y
  end
  attribute \src "state_machine2.v:88"
  cell $logic_not $logic_not$state_machine2.v:88$119
    parameter \A_SIGNED 0
    parameter \A_WIDTH 1
    parameter \Y_WIDTH 1
    connect \A \irdy
    connect \Y $logic_not$state_machine2.v:88$119_Y
  end
  attribute \src "state_machine2.v:35"
  process $proc$state_machine2.v:35$108
    assign { } { }
    assign $0\fcount[0:0] \fcount
    assign $0\fend_count[0:0] \fend_count
    assign $0\freq_pending[0:0] \freq_pending
    assign $0\ffinished[0:0] \ffinished
    assign $0\fgnt[0:0] \fgnt
    assign $0\state[2:0] \next_state
    attribute \src "state_machine2.v:37"
    switch \force_req
      case 1'1
        assign $0\fend_count[0:0] 1'0
        assign $0\fcount[0:0] 1'1
      case 
    end
    attribute \src "state_machine2.v:41"
    switch $logic_and$state_machine2.v:41$110_Y
      case 1'1
        assign $0\fcount[0:0] 1'0
        assign $0\fend_count[0:0] 1'1
      case 
    end
    attribute \src "state_machine2.v:45"
    switch $logic_and$state_machine2.v:45$112_Y
      case 1'1
        assign $0\fgnt[0:0] 1'0
        assign $0\freq_pending[0:0] 1'1
      case 
    end
    attribute \src "state_machine2.v:49"
    switch \req
      case 1'1
        assign $0\freq_pending[0:0] 1'0
      case 
    end
    attribute \src "state_machine2.v:52"
    switch $eq$state_machine2.v:52$113_Y
      case 1'1
        assign $0\freq_pending[0:0] 1'0
        assign $0\ffinished[0:0] 1'0
      case 
    end
    attribute \src "state_machine2.v:56"
    switch $eq$state_machine2.v:56$114_Y
      case 1'1
        assign $0\ffinished[0:0] 1'1
      case 
    end
    attribute \src "state_machine2.v:59"
    switch $logic_not$state_machine2.v:59$115_Y
      case 1'1
        assign $0\fgnt[0:0] 1'1
      case 
    end
    sync negedge \clk
      update \state $0\state[2:0]
      update \fcount $0\fcount[0:0]
      update \fend_count $0\fend_count[0:0]
      update \freq_pending $0\freq_pending[0:0]
      update \ffinished $0\ffinished[0:0]
      update \fgnt $0\fgnt[0:0]
  end
  attribute \src "state_machine2.v:64"
  process $proc$state_machine2.v:64$116
    assign { } { }
    assign { } { }
    assign $0\fvalid[0:0] $1\fvalid[0:0]
    assign $0\next_state[2:0] $1\next_state[2:0]
    attribute \src "state_machine2.v:65"
    switch \state
      case 3'000
        assign $1\fvalid[0:0] \fvalid
        assign { } { }
        assign $1\next_state[2:0] $2\next_state[2:0]
        attribute \src "state_machine2.v:67"
        switch \fgnt
          case 1'1
            assign { } { }
            assign $2\next_state[2:0] 3'001
          case 
            assign $2\next_state[2:0] \next_state
        end
      case 3'001
        assign $1\fvalid[0:0] \fvalid
        assign { } { }
        assign $1\next_state[2:0] $3\next_state[2:0]
        attribute \src "state_machine2.v:71"
        switch $logic_not$state_machine2.v:71$117_Y
          case 1'1
            assign { } { }
            assign $3\next_state[2:0] $4\next_state[2:0]
            attribute \src "state_machine2.v:72"
            switch \rd_wr
              case 1'1
                assign { } { }
                assign $4\next_state[2:0] 3'010
              case 
                assign { } { }
                assign $4\next_state[2:0] 3'011
            end
          case 
            assign $3\next_state[2:0] \next_state
        end
      case 3'010
        assign $1\fvalid[0:0] \fvalid
        assign { } { }
        assign $1\next_state[2:0] 3'011
      case 3'011
        assign { } { }
        assign { } { }
        assign $1\next_state[2:0] $5\next_state[2:0]
        assign $1\fvalid[0:0] $2\fvalid[0:0]
        attribute \src "state_machine2.v:85"
        switch \frame
          case 1'1
            assign { } { }
            assign $5\next_state[2:0] 3'100
          case 
            assign $5\next_state[2:0] \next_state
        end
        attribute \src "state_machine2.v:88"
        switch $logic_and$state_machine2.v:88$120_Y
          case 1'1
            assign { } { }
            assign $2\fvalid[0:0] 1'1
          case 
            assign { } { }
            assign $2\fvalid[0:0] 1'0
        end
      case 3'100
        assign $1\fvalid[0:0] \fvalid
        assign { } { }
        assign $1\next_state[2:0] 3'000
      case 
        assign $1\fvalid[0:0] \fvalid
        assign { } { }
        assign $1\next_state[2:0] 3'000
    end
    sync always
      update \fvalid $0\fvalid[0:0]
      update \next_state $0\next_state[2:0]
  end
end
attribute \cells_not_processed 1
attribute \src "target.v:1"
module \Target_Controller
  parameter \address
  parameter \data
  parameter \devaddress
  parameter \finish
  parameter \idle
  parameter \read
  parameter \turnaround
  parameter \write
  attribute \src "target.v:14"
  wire width 32 $0\add[31:0]
  attribute \src "target.v:14"
  wire width 4 $0\command[3:0]
  attribute \src "target.v:14"
  wire width 32 $0\memory[31:0]
  attribute \src "target.v:15"
  wire $eq$target.v:15$80_Y
  attribute \src "target.v:19"
  wire $eq$target.v:19$81_Y
  attribute \src "target.v:19"
  wire $eq$target.v:19$82_Y
  attribute \src "target.v:35"
  wire $eq$target.v:35$84_Y
  attribute \src "target.v:35"
  wire $eq$target.v:35$85_Y
  attribute \src "target.v:35"
  wire $eq$target.v:35$87_Y
  attribute \src "target.v:35"
  wire $eq$target.v:35$88_Y
  attribute \src "target.v:36"
  wire $eq$target.v:36$93_Y
  attribute \src "target.v:36"
  wire $eq$target.v:36$94_Y
  attribute \src "target.v:36"
  wire $eq$target.v:36$96_Y
  attribute \src "target.v:36"
  wire $eq$target.v:36$97_Y
  attribute \src "target.v:37"
  wire $eq$target.v:37$102_Y
  attribute \src "target.v:37"
  wire $eq$target.v:37$103_Y
  attribute \src "target.v:37"
  wire $eq$target.v:37$105_Y
  attribute \src "target.v:35"
  wire width 32 $extend$target.v:35$90_Y
  attribute \src "target.v:36"
  wire width 32 $extend$target.v:36$99_Y
  attribute \src "target.v:19"
  wire $logic_and$target.v:19$83_Y
  attribute \src "target.v:35"
  wire $logic_and$target.v:35$86_Y
  attribute \src "target.v:36"
  wire $logic_and$target.v:36$95_Y
  attribute \src "target.v:37"
  wire $logic_and$target.v:37$104_Y
  attribute \src "target.v:37"
  wire $logic_and$target.v:37$106_Y
  attribute \src "target.v:35"
  wire $logic_or$target.v:35$89_Y
  attribute \src "target.v:36"
  wire $logic_or$target.v:36$98_Y
  attribute \src "target.v:35"
  wire width 32 $ternary$target.v:35$91_Y
  attribute \src "target.v:35"
  wire width 32 $ternary$target.v:35$92_Y
  attribute \src "target.v:36"
  wire width 32 $ternary$target.v:36$100_Y
  attribute \src "target.v:36"
  wire width 32 $ternary$target.v:36$101_Y
  attribute \src "target.v:37"
  wire width 32 $ternary$target.v:37$107_Y
  attribute \src "target.v:2"
  wire width 32 inout 2 \AD
  attribute \src "target.v:2"
  wire width 4 input 3 \C_BE
  attribute \src "target.v:11"
  wire width 32 \add
  attribute \src "target.v:2"
  wire input 1 \clk
  attribute \src "target.v:13"
  wire width 4 \command
  attribute \src "target.v:2"
  wire output 4 \devsel
  attribute \src "target.v:2"
  wire input 7 \fvalid
  attribute \src "target.v:12"
  wire width 32 \memory
  attribute \src "target.v:2"
  wire width 3 input 6 \state
  attribute \src "target.v:2"
  wire output 5 \trdy
  attribute \src "target.v:15"
  cell $eq $eq$target.v:15$80
    parameter \A_SIGNED 0
    parameter \A_WIDTH 3
    parameter \B_SIGNED 0
    parameter \B_WIDTH 3
    parameter \Y_WIDTH 1
    connect \A \state
    connect \B 3'001
    connect \Y $eq$target.v:15$80_Y
  end
  attribute \src "target.v:19"
  cell $eq $eq$target.v:19$81
    parameter \A_SIGNED 0
    parameter \A_WIDTH 3
    parameter \B_SIGNED 0
    parameter \B_WIDTH 3
    parameter \Y_WIDTH 1
    connect \A \state
    connect \B 3'011
    connect \Y $eq$target.v:19$81_Y
  end
  attribute \src "target.v:19"
  cell $eq $eq$target.v:19$82
    parameter \A_SIGNED 0
    parameter \A_WIDTH 4
    parameter \B_SIGNED 0
    parameter \B_WIDTH 4
    parameter \Y_WIDTH 1
    connect \A \command
    connect \B 4'0000
    connect \Y $eq$target.v:19$82_Y
  end
  attribute \src "target.v:35"
  cell $eq $eq$target.v:35$84
    parameter \A_SIGNED 0
    parameter \A_WIDTH 3
    parameter \B_SIGNED 0
    parameter \B_WIDTH 3
    parameter \Y_WIDTH 1
    connect \A \state
    connect \B 3'011
    connect \Y $eq$target.v:35$84_Y
  end
  attribute \src "target.v:35"
  cell $eq $eq$target.v:35$85
    parameter \A_SIGNED 0
    parameter \A_WIDTH 32
    parameter \B_SIGNED 0
    parameter \B_WIDTH 32
    parameter \Y_WIDTH 1
    connect \A \add
    connect \B 1
    connect \Y $eq$target.v:35$85_Y
  end
  attribute \src "target.v:35"
  cell $eq $eq$target.v:35$87
    parameter \A_SIGNED 0
    parameter \A_WIDTH 3
    parameter \B_SIGNED 0
    parameter \B_WIDTH 3
    parameter \Y_WIDTH 1
    connect \A \state
    connect \B 3'100
    connect \Y $eq$target.v:35$87_Y
  end
  attribute \src "target.v:35"
  cell $eq $eq$target.v:35$88
    parameter \A_SIGNED 0
    parameter \A_WIDTH 3
    parameter \B_SIGNED 0
    parameter \B_WIDTH 3
    parameter \Y_WIDTH 1
    connect \A \state
    connect \B 3'010
    connect \Y $eq$target.v:35$88_Y
  end
  attribute \src "target.v:36"
  cell $eq $eq$target.v:36$93
    parameter \A_SIGNED 0
    parameter \A_WIDTH 3
    parameter \B_SIGNED 0
    parameter \B_WIDTH 3
    parameter \Y_WIDTH 1
    connect \A \state
    connect \B 3'011
    connect \Y $eq$target.v:36$93_Y
  end
  attribute \src "target.v:36"
  cell $eq $eq$target.v:36$94
    parameter \A_SIGNED 0
    parameter \A_WIDTH 32
    parameter \B_SIGNED 0
    parameter \B_WIDTH 32
    parameter \Y_WIDTH 1
    connect \A \add
    connect \B 1
    connect \Y $eq$target.v:36$94_Y
  end
  attribute \src "target.v:36"
  cell $eq $eq$target.v:36$96
    parameter \A_SIGNED 0
    parameter \A_WIDTH 3
    parameter \B_SIGNED 0
    parameter \B_WIDTH 3
    parameter \Y_WIDTH 1
    connect \A \state
    connect \B 3'100
    connect \Y $eq$target.v:36$96_Y
  end
  attribute \src "target.v:36"
  cell $eq $eq$target.v:36$97
    parameter \A_SIGNED 0
    parameter \A_WIDTH 3
    parameter \B_SIGNED 0
    parameter \B_WIDTH 3
    parameter \Y_WIDTH 1
    connect \A \state
    connect \B 3'010
    connect \Y $eq$target.v:36$97_Y
  end
  attribute \src "target.v:37"
  cell $eq $eq$target.v:37$102
    parameter \A_SIGNED 0
    parameter \A_WIDTH 3
    parameter \B_SIGNED 0
    parameter \B_WIDTH 3
    parameter \Y_WIDTH 1
    connect \A \state
    connect \B 3'011
    connect \Y $eq$target.v:37$102_Y
  end
  attribute \src "target.v:37"
  cell $eq $eq$target.v:37$103
    parameter \A_SIGNED 0
    parameter \A_WIDTH 32
    parameter \B_SIGNED 0
    parameter \B_WIDTH 32
    parameter \Y_WIDTH 1
    connect \A \add
    connect \B 1
    connect \Y $eq$target.v:37$103_Y
  end
  attribute \src "target.v:37"
  cell $eq $eq$target.v:37$105
    parameter \A_SIGNED 0
    parameter \A_WIDTH 4
    parameter \B_SIGNED 0
    parameter \B_WIDTH 4
    parameter \Y_WIDTH 1
    connect \A \command
    connect \B 4'0001
    connect \Y $eq$target.v:37$105_Y
  end
  attribute \src "target.v:35"
  cell $pos $extend$target.v:35$90
    parameter \A_SIGNED 0
    parameter \A_WIDTH 1
    parameter \Y_WIDTH 32
    connect \A 1'z
    connect \Y $extend$target.v:35$90_Y
  end
  attribute \src "target.v:36"
  cell $pos $extend$target.v:36$99
    parameter \A_SIGNED 0
    parameter \A_WIDTH 1
    parameter \Y_WIDTH 32
    connect \A 1'z
    connect \Y $extend$target.v:36$99_Y
  end
  attribute \src "target.v:19"
  cell $logic_and $logic_and$target.v:19$83
    parameter \A_SIGNED 0
    parameter \A_WIDTH 1
    parameter \B_SIGNED 0
    parameter \B_WIDTH 1
    parameter \Y_WIDTH 1
    connect \A $eq$target.v:19$81_Y
    connect \B $eq$target.v:19$82_Y
    connect \Y $logic_and$target.v:19$83_Y
  end
  attribute \src "target.v:35"
  cell $logic_and $logic_and$target.v:35$86
    parameter \A_SIGNED 0
    parameter \A_WIDTH 1
    parameter \B_SIGNED 0
    parameter \B_WIDTH 1
    parameter \Y_WIDTH 1
    connect \A $eq$target.v:35$84_Y
    connect \B $eq$target.v:35$85_Y
    connect \Y $logic_and$target.v:35$86_Y
  end
  attribute \src "target.v:36"
  cell $logic_and $logic_and$target.v:36$95
    parameter \A_SIGNED 0
    parameter \A_WIDTH 1
    parameter \B_SIGNED 0
    parameter \B_WIDTH 1
    parameter \Y_WIDTH 1
    connect \A $eq$target.v:36$93_Y
    connect \B $eq$target.v:36$94_Y
    connect \Y $logic_and$target.v:36$95_Y
  end
  attribute \src "target.v:37"
  cell $logic_and $logic_and$target.v:37$104
    parameter \A_SIGNED 0
    parameter \A_WIDTH 1
    parameter \B_SIGNED 0
    parameter \B_WIDTH 1
    parameter \Y_WIDTH 1
    connect \A $eq$target.v:37$102_Y
    connect \B $eq$target.v:37$103_Y
    connect \Y $logic_and$target.v:37$104_Y
  end
  attribute \src "target.v:37"
  cell $logic_and $logic_and$target.v:37$106
    parameter \A_SIGNED 0
    parameter \A_WIDTH 1
    parameter \B_SIGNED 0
    parameter \B_WIDTH 1
    parameter \Y_WIDTH 1
    connect \A $logic_and$target.v:37$104_Y
    connect \B $eq$target.v:37$105_Y
    connect \Y $logic_and$target.v:37$106_Y
  end
  attribute \src "target.v:35"
  cell $logic_or $logic_or$target.v:35$89
    parameter \A_SIGNED 0
    parameter \A_WIDTH 1
    parameter \B_SIGNED 0
    parameter \B_WIDTH 1
    parameter \Y_WIDTH 1
    connect \A $eq$target.v:35$87_Y
    connect \B $eq$target.v:35$88_Y
    connect \Y $logic_or$target.v:35$89_Y
  end
  attribute \src "target.v:36"
  cell $logic_or $logic_or$target.v:36$98
    parameter \A_SIGNED 0
    parameter \A_WIDTH 1
    parameter \B_SIGNED 0
    parameter \B_WIDTH 1
    parameter \Y_WIDTH 1
    connect \A $eq$target.v:36$96_Y
    connect \B $eq$target.v:36$97_Y
    connect \Y $logic_or$target.v:36$98_Y
  end
  attribute \src "target.v:35"
  cell $mux $ternary$target.v:35$91
    parameter \WIDTH 32
    connect \A $extend$target.v:35$90_Y
    connect \B 1
    connect \S $logic_or$target.v:35$89_Y
    connect \Y $ternary$target.v:35$91_Y
  end
  attribute \src "target.v:35"
  cell $mux $ternary$target.v:35$92
    parameter \WIDTH 32
    connect \A $ternary$target.v:35$91_Y
    connect \B 0
    connect \S $logic_and$target.v:35$86_Y
    connect \Y $ternary$target.v:35$92_Y
  end
  attribute \src "target.v:36"
  cell $mux $ternary$target.v:36$100
    parameter \WIDTH 32
    connect \A $extend$target.v:36$99_Y
    connect \B 1
    connect \S $logic_or$target.v:36$98_Y
    connect \Y $ternary$target.v:36$100_Y
  end
  attribute \src "target.v:36"
  cell $mux $ternary$target.v:36$101
    parameter \WIDTH 32
    connect \A $ternary$target.v:36$100_Y
    connect \B 0
    connect \S $logic_and$target.v:36$95_Y
    connect \Y $ternary$target.v:36$101_Y
  end
  attribute \src "target.v:37"
  cell $mux $ternary$target.v:37$107
    parameter \WIDTH 32
    connect \A 32'zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz
    connect \B 32'10101010101010101010101010101010
    connect \S $logic_and$target.v:37$106_Y
    connect \Y $ternary$target.v:37$107_Y
  end
  attribute \src "target.v:14"
  process $proc$target.v:14$79
    assign $0\command[3:0] \command
    assign $0\memory[31:0] \memory
    assign $0\add[31:0] \add
    attribute \src "target.v:15"
    switch $eq$target.v:15$80_Y
      case 1'1
        assign $0\add[31:0] \AD
        assign $0\command[3:0] \C_BE
      case 
    end
    attribute \src "target.v:19"
    switch $logic_and$target.v:19$83_Y
      case 1'1
        attribute \src "target.v:20"
        switch \C_BE [0]
          case 1'1
            assign $0\memory[31:0] [7:0] \AD [7:0]
          case 
        end
        attribute \src "target.v:23"
        switch \C_BE [1]
          case 1'1
            assign $0\memory[31:0] [15:8] \AD [15:8]
          case 
        end
        attribute \src "target.v:26"
        switch \C_BE [2]
          case 1'1
            assign $0\memory[31:0] [23:16] \AD [23:16]
          case 
        end
        attribute \src "target.v:29"
        switch \C_BE [3]
          case 1'1
            assign $0\memory[31:0] [31:24] \AD [31:24]
          case 
        end
      case 
    end
    sync posedge \clk
      update \command $0\command[3:0]
      update \memory $0\memory[31:0]
      update \add $0\add[31:0]
  end
  connect \devsel $ternary$target.v:35$92_Y [0]
  connect \trdy $ternary$target.v:36$101_Y [0]
  connect \AD $ternary$target.v:37$107_Y
end
